using System.ComponentModel;

namespace OpenWeatherMap.Core.Enums {
	public enum Language {
		[Description("af")]
		Afrikaans,
		[Description("al")]
		Albanian,
		[Description("ar")]
		Arabic,
		[Description("az")]
		Azerbaijani,
		[Description("bg")]
		Bulgarian,
		[Description("ca")]
		Catalan,
		[Description("cz")]
		Czech,
		[Description("da")]
		Danish,
		[Description("de")]
		German,
		[Description("el")]
		Greek,
		[Description("en")]
		English,
		[Description("eu")]
		Basque,
		[Description("fa")]
		Persian,
		[Description("fi")]
		Finnish,
		[Description("fr")]
		French,
		[Description("gl")]
		Galician,
		[Description("he")]
		Hebrew,
		[Description("hi")]
		Hindi,
		[Description("hr")]
		Croatian,
		[Description("hu")]
		Hungarian,
		[Description("id")]
		Indonesian,
		[Description("it")]
		Italian,
		[Description("ja")]
		Japanese,
		[Description("kr")]
		Korean,
		[Description("la")]
		Latvian,
		[Description("lt")]
		Lithuanian,
		[Description("mk")]
		Macedonian,
		[Description("no")]
		Norwegian,
		[Description("nl")]
		Dutch,
		[Description("pl")]
		Polish,
		[Description("pt")]
		Portuguese,
		[Description("pt_br")]
		Português_Brasil,
		[Description("ro")]
		Romanian,
		[Description("ru")]
		Russian,
		[Description("sv")]
		Swedish,
		[Description("sk")]
		Slovak,
		[Description("sl")]
		Slovenian,
		[Description("es")]
		Spanish,
		[Description("sr")]
		Serbian,
		[Description("th")]
		Thai,
		[Description("tr")]
		Turkish,
		[Description("ua")]
		Ukrainian,
		[Description("vi")]
		Vietnamese,
		[Description("zh_cn")]
		Chinese_Simplified,
		[Description("zh_tw")]
		Chinese_Traditional,
		[Description("zu")]
		Zulu
	}
}